-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 15:55:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `usuario` VARCHAR(80) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `correo_electronico` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_doc` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_doc` (
  `id_tipo_doc` INT NOT NULL,
  `tipodocumento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_tipo_doc`),
  UNIQUE INDEX `id_tipo_doc_UNIQUE` (`id_tipo_doc` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `nit_proveedor` VARCHAR(80) NOT NULL,
  `nombre_pro` VARCHAR(100) NOT NULL,
  `correo_pro` VARCHAR(150) NOT NULL,
  `telefono_pro` VARCHAR(70) NOT NULL,
  `ciudad_pro` VARCHAR(100) NOT NULL,
  `direccion_pro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nit_proveedor`),
  UNIQUE INDEX `nit_proveedor_UNIQUE` (`nit_proveedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contabilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contabilidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contabilidad` (
  `dia_contable` DATE NOT NULL,
  `venta` DECIMAL(40) NOT NULL,
  `administrador_usuario` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`dia_contable`),
  INDEX `fk_contabilidad_administrador1_idx` (`administrador_usuario` ASC) VISIBLE,
  UNIQUE INDEX `dia_contable_UNIQUE` (`dia_contable` ASC) VISIBLE,
  UNIQUE INDEX `administrador_usuario_UNIQUE` (`administrador_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_contabilidad_administrador1`
    FOREIGN KEY (`administrador_usuario`)
    REFERENCES `mydb`.`administrador` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `numero_documento_emp` VARCHAR(100) NOT NULL,
  `nombre_emp` VARCHAR(100) NOT NULL,
  `apellidos_emp` VARCHAR(100) NOT NULL,
  `telefono_emp` VARCHAR(70) NOT NULL,
  `correo_emp` VARCHAR(150) NOT NULL,
  `ciudad_emp` VARCHAR(100) NOT NULL,
  `direccion_emp` VARCHAR(100) NOT NULL,
  `id_tipo_doc` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_tipo_doc1_idx` (`id_tipo_doc` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tipo_doc1`
    FOREIGN KEY (`id_tipo_doc`)
    REFERENCES `mydb`.`tipo_doc` (`id_tipo_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `codigo_producto` VARCHAR(200) NOT NULL,
  `nombre_produc` VARCHAR(100) NOT NULL,
  `precio_produc` DECIMAL(40) NOT NULL,
  `dia_produc` TIMESTAMP(6) NOT NULL,
  `administrador_usuario` VARCHAR(80) NOT NULL,
  `nit_proveedor` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codigo_producto`),
  INDEX `fk_inventario_administrador1_idx` (`administrador_usuario` ASC) VISIBLE,
  INDEX `fk_inventario_proveedores1_idx` (`nit_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_administrador1`
    FOREIGN KEY (`administrador_usuario`)
    REFERENCES `mydb`.`administrador` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_proveedores1`
    FOREIGN KEY (`nit_proveedor`)
    REFERENCES `mydb`.`proveedores` (`nit_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
